### ISSUE TITLE
Small refactoring requests

### ISSUE THREAD

**Issue by yotahk** [yota-p/kaggle_ieee-fraud-detection#12]
## Description
This is a issue to gather small refactoring requests to improve productivity. 
Add them in this issue and will be modified at once. 

Note: This issue will accept **up to 5 requests**. 
Each requests should be able to be fixed **within 20 lines** of coding. 
Unsuitable tasks will not be fixed in this issue. 

## Goal
To complete all requests in this issue. 

## Impact
Usability imporvement. 

### Change output directory of lightgbm oof
Currently oof training data is being outputted to src/ directory, which is not for output. 
Change output directory to log/train/. 

### Gather key path
Key files like .slack_token, .kaggle.json are dispersed in the project or system directory. 
I need to gather keys to one directory to make them manageable. 

### Remove AbstractTask.py
Currently class AbstractTask() is for just forcing it's inheritors to implement output() and run(). 
This is replaceable by luigi.Task(), so AbstractTask is no longer needed. 

## Tasks
- [ ] Change output directory of lightgbm oof
- [ ] Gather Key path
- [ ] Remove AbstractTask.py

**Comment by yotahk** [comment]
This issue was solved by #16 
close #12
