### ISSUE TITLE
Log validation scores at each steps

### ISSUE THREAD

**Issue by yotahk** [yota-p/kaggle_ieee-fraud-detection#22]
## Description
Current log file doesn’t include evaluation scores at each steps.

## Goal
Evaluation scores are logged in each log files.

## Impact
Able to analyze score variation over steps

## Reference
None

## Additional
None

## Tasks

- [x] On lgb
  - [x] Create lgb exclusive logger creating & getting method on trainer
  - [x] Organize model parameters
  - [x] move unneeded messages to main logger
  - [x] Specify digits for scores on train logger
  - [x] Output fold on train logger
- [x] Apply same things to xgb
- [x] Swich to small datasets if debug mode
- [x] Consistency check for lgb, xgb
