### ISSUE TITLE
Organize directory

### ISSUE THREAD

**Issue by yotahk** [yota-p/kaggle_ieee-fraud-detection#28]
## Description
Current directory is having datas at top level, though 

## Goal
Finish Tasks below

## Impact
Better access to each files. 
Remove unneeded files. 

## Reference
None

## Additional
This is how the directories will look like:
(move src/* to top, remove 's' from directory name, data in data/*) 
```
data/model *ignore
data/submission *ignore
data/raw *ignore
data/feature *ignore
log/train_0000.tsv
log/main_0000.log
log/importance_0000.json
log/params_0000.json
util/
feature/
config/
run0000.py
...
run9999.py
```

## Tasks
- [x] Remove make requirements, dir, run*, test, test_environment from Makefile
- [x] Change print in reduce_mem_usage into logger
- [x] Check run 0007
- [x] move transformer to utils, feature_factory to features
- [x] Change directories as above
  - [x] move dir & grep for adjust & adjust code & run for each:
    - [x] models->data/model
    - [x] data/submission (no need of modification)
    - [x] data/raw (no need of modification)
    - [x] data/processed->data/feature
    - [x] data/interim->delete
    - [x] data/external->delete
    - [x] log/train/0000.tsv->log/train_0000.tsv
    - [x] log/main/0000.log->log/main_0000.log
    - [x] log/importance_0000.json (no files to rewrite)
    - [x] log/params_0000.json (no files to rewrite)
    - [x] src/utils->util/
    - [x] src/features->feature/
    - [x] src/config->config/
    - [x] src/models->model/
    - [x] src/run->run0000.py
    - [x] notebooks->notebook
- [x] .gitignore data
- [x] .gitkeep data/DIR
- [x] remove unneccesary sys.path.insert()  - [x] Check run 0007
- [x] Define paths at config as possible
  - [x] data/feature/EACHFEATURE *this needs to be single executable. need to define dir in script
  - [x] data/feature/MERGED
  - [x] data/model *model_name will be determined from model.TYPE
  - [x] data/raw  *this needs to be single executable. need to define dir in script
  - [x] data/submission
  - [x] log/main, train
- [x] Create submission shell script & run from make -> couldn't pass variables properly so decided to leave memo and use command to submit.
