### ISSUE TITLE
Organize model and trainer

### ISSUE THREAD

**Issue by yotahk** [yota-p/kaggle_ieee-fraud-detection#30]
## Description
GBDT models (LightGBM, XGBoost, CatBoost) have similar but slightly different methods.
Let's use them at same procedure. 

## Goal
To Switch models from config
i.e. To finish the tasks below. 

## Impact
Easy to switch GBDT models. 

## Reference
None

## Additional
None

## Tasks
- [x] Deprecate configure.py
  - [x] Create utils.easydict
  - [x] Create utils.option
  - [x] Apply option at run.py
- [x] At run:
  - [x] Create modelfactory
  - [x] Create defaultmodel
  - [x] tune
  - [x] Create tunedmodel
  - [x] train
  - [x] predict
- [x] At script:
  - [x] Create method train at run
  - [x] Create method tune_params at run
- [x] Create model.ModelFactory
- [x] Create model.BaseModel
- [x] Create model.LightGBM_Model
- [x] Create model.XGBoost_Model(hollow class)
- [x] run 0007
- [x] Remove LGBMTrainer
- [x] Remove BaseTrainer
- [x] Save  model as name: model_0000_TYPE.pkl
- [x] Save feature importance
- [x] Create model.XGBoost_Model
- [x] run 0008
