### ISSUE TITLE
Define filename by run

### ISSUE THREAD

**Issue by yotahk** [yota-p/kaggle_ieee-fraud-detection#32]
## Description
Currently output filename is defined at both config and run. 
Directory structure(log/, data/...) requires filenames to be determined on certain rules, thus defining filename at config is not necessary. 
In this issue, naming rules will be defined, and modify configs not to define filenames, dirs. 

## Goal
Define filenames based on RULE below:

***RULE***
{filetype}_{VERSION}(.small){.extention}
```
data/feature/name_test(.small).pkl
data/feature/name_train(.small).pkl
data/raw/*.csv
data/model/model_0000(.small).json
data/submission/submission_0000.csv
log/main_0000(.small).log
log/train_0000(.small).tsv
```

## Impact
Config file to be slim. 
Dynamically change filename at run_{VERSION}.py. 

## Reference
None

## Additional
- [x] utilize method islatest
- [x] output option to log
- [x] remove print() from source
- [x] remove TODO from source
- [x] remove unneeded lines (unused modules, comment outs)
- [x] remove RUN_TRAIN, RUN_PRED from config
- [x] Deprecate 0000-0009

## Tasks
- [x] search data input/output
- [x] Implement rules
  - [x] Create run_0010.py (copy of 0009)
  - [x] Comment out paths from config
  - [x] set filenames at run_0010.py
  - [x] separate output (*.small) from full data
    - [x] move value c.transfromer.USE_SMALL_DATA to c.runtime
    - [x] Modify all file input & output methods
  - [x] run 0010, compare output to 0009
- [x] Add data reading methods to debugging notebook (based on RULE above)

**Comment by yotahk** [comment]
## Search result for data input/output:

### config.py
out_sub_path
out_train_path -> out_transformed_train_path # change name
out_test_path -> out_transformed_test_path # change name
model.dir
main_log_path
train_log_path

### run.py
model_0000_TYPE.pkl
model_0000_TYPE_fold0.pkl
importance_0000.csv

**Comment by yotahk** [comment]
## Remove print()
Method print() in magic.py is torelated, because it's originally used at notebook to show progress & only valid when verbose=True. Doesn't effect a lot even it's not logged.

**Comment by yotahk** [comment]
## Utilize isLatest()
used at:
feature_base.py
transformer.py
