### ISSUE TITLE
Small enhancements

### ISSUE THREAD

**Issue by yotahk** [yota-p/kaggle_ieee-fraud-detection#36]
## Description
Small enhancements

## Goal
- [x] deprecate c.runtime
- [x] reduce Slack notification
- [x] use JSON for configs

## Impact
None

## Reference
None

## Additional
None

## Tasks
- [x] copy 0010 as 0012, 0011 as 0013
- [x] deprecate c.runtime on config
  - [x] deprecate ROOTDIR (use relative path)
  - [x] RANDOM_SEED to args
  - [x] USE_SMALL_DATA to args
  - [x] VERSION from command line args
  - [x] indicate config by command line args
- [x] separate config.slackauth
- [x] reduce Slack notification - by optional args for timer
- [x] FILE, SLACK, STREAM_HANDLER_LEVEL to small letters
- [x] use JSON for config
  - [x] create slackauth.json
  - [x] read slackauth.json from run_gbdt.py
  - [x] deprecate np.nan from missing (magic.py, config_0012.py)
  - [x] create config_0012.json, config_0013.json
  - [x] read config_0012.json, config_0013.json from run_gbdt.py
  - [x] deprecate pathlib.Path as normal use. Use it for is_latest only
- [x] confirm consistency
