### ISSUE TITLE
Reproduce 1st place solution

### ISSUE THREAD

**Issue by yotahk** [yota-p/kaggle_ieee-fraud-detection#38]
## Description
Currently my highest score is Private 0.932896, Public 0.958595. 
1st place solution is 0.967722 public, 0.945884 private. 

## Goal
To achieve Private score > 0.945884. 

- Catboost (0.963915 public / 0.940826 private)
- LGBM (0.961748 / 0.938359)
- XGB (0.960205 / 0.932369)

## Impact
Proof of correct model. 

## Reference
1st Place Solution - Part 1
https://www.kaggle.com/c/ieee-fraud-detection/discussion/111284

1st Place Solution - Part 2
https://www.kaggle.com/c/ieee-fraud-detection/discussion/111308

Very short summary
https://www.kaggle.com/c/ieee-fraud-detection/discussion/111257

IEEE - Notebooks series (LB 0.9480/no blend)
https://www.kaggle.com/c/ieee-fraud-detection/discussion/104142

How to find UIDs
https://www.kaggle.com/c/ieee-fraud-detection/discussion/111510

How the magic works
https://www.kaggle.com/c/ieee-fraud-detection/discussion/111453

XGB Fraud with Magic - [0.9600]
https://www.kaggle.com/cdeotte/xgb-fraud-with-magic-0-9600

Kaggle Ensembling Guide
https://mlwave.com/kaggle-ensembling-guide/

## Additional
None

## Tasks
- [x] Check reference
- [x] How to validate -> GroudKfold by month 'DT_M'
- [x] Fix diffs from reference kernels
- [x] Create features by Cdeotte's notebook
- [x] Run xgboost by batch
- [x] Run lightgbm by batch
- [x] Run catboost by batch
- [x] Blend submissions
- [x] Divide scripts by objective
- [x] Output evals_result to file
- [ ] Deprecate callbacks, train_log
- [x] Hyper parameter tune
- [x] Use mlflow
- [ ] ~~Confirm Private score > 0.945884.~~

**Comment by yotahk** [comment]
Reproducing the kernel in batch needs some refactoring, which causes small differences to the result. I'll use notebooks for FE.

**Comment by yotahk** [comment]
Using Cdeotte's feature: 
Version Model Private Public
0013 LightGBM 0.933593 0.958895
0014 XGBoost 0.921008 0.950186
0015 CatBoost 0.923884 0.949718

Ensemble 1:1:1 0.930987 0.956657 # Just a bit better.

**Comment by yotahk** [comment]
Hyper parameters tuning didn't perform better than the winner's solution.

**Comment by yotahk** [comment]
Although my models couldn't reproduce 1st place solution perfectly, it performed good enough in terms of AUC score. There's no meaning to searching for further difference between the kernel and my batch. This issue to be closed.
