### ISSUE TITLE
Create test code

### ISSUE THREAD

**Issue by yotahk** [yota-p/kaggle_ieee-fraud-detection#4]
## Description
This project doesn't have a test code. 
Need a test suite for essential modules. 

## Goal
One can run test suite by ```make test```.

## Impact
Keep codes consistent to existing functions. 
Reduce bugs in production code. 
Reduce time for bug fixing. 

## Tasks
- [ ] Dig up modules to test
- [ ] Implement ```make test```
- [ ] Implement test cases
  - [ ] module1, 2, ...

**Comment by yotahk** [comment]
This will be implemented in next project.
