### ISSUE TITLE
Divide model into Model, ModelAPI, Trainer

### ISSUE THREAD

**Issue by yotahk** [yota-p/kaggle_ieee-fraud-detection#6]
## Description
Currently the models are called directly from the training method. 
Thus model & library specific codes are having dense union to the common code. 
I want to call model using common method. 

## Goal
Model & library specific codes not implemented out of src/model. 
Create two models implementing Model, Trainer, ModelAPI. 
Can change model from config (without modifying the code!)

## Impact
Be able to handle different models using same method. 
Reduce risks of changing improper codes. 

## Reference
Use architecture from TIS Kubo. 
[TIS_Kubo_2016](https://www.slideshare.net/takahirokubo7792/ss-65413290)
[TIS_Kubo_2018](https://www.slideshare.net/takahirokubo7792/2018-97367311)

## Additional
Each models contain Model, Trainer, ModelAPI. 
Class Model implements the model & library specific codes. 
To train: Trainer.train() calls Model.train()
To predict: ModelAPI.predict() calls Model.predict()

## Tasks
- [ ] Create AbstractClass of ModelAPI, Trainer
- [ ] Implement lightgbm into Model, ModelAPI, Trainer
- [ ] Implement NN into Model, ModelAPI, Trainer
- [ ] Choose model from config file

**Comment by yotahk** [comment]
This issue was solved in #16.
close #6
